apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: secure-app
subjects:
  - kind: ServiceAccount
    name: app-sa
    namespace: secure-app
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
