apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: secure-app
type: Opaque
data:
  username: YWRtaW4=          # base64 of "admin"
  password: c2VjdXJlcGFzcw==  # base64 of "securepass"
  root_password: cm9vdHBhc3M= # base64 of "rootpass"
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: secure-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoicmFqZXNodGh1bGFzaXJhbSIsInBhc3N3b3JkIjoiZ2hwX0YydWVXTjBSakVYZnZoZDBORjk4dzZ4NEpxWkRYdTBaZWg2eCIsImVtYWlsIjoicmFqZXNoc2FpMDc5QGdtYWlsLmNvbSIsImF1dGgiOiJjbUZxWlhOb2RHaDFiR0Z6YVhKaGJUcG5hSEJmUmpKMVpWZE9NRkpxUlZobWRtaGtNRTVHT1RoM05uZzBTbkZhUkZoMU1GcGxhRFo0In19fQ==  # Use `kubectl create secret docker-registry` to generate
