apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: secure-app
  labels:
    app: backend
    role: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        role: backend
    spec:
      serviceAccountName: app-sa
      containers:
        - name: backend
          image: ghcr.io/rajeshthulasiram/backend:latest
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: DB_HOST
              value: mysql                    # Refers to the MySQL service
            - name: DB_PORT
              value: "3306"                   # MySQL default port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
