apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: secure-app
  labels:
    app: mysql
    role: database
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  type: ClusterIP
