apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: secure-app
  labels:
    app: frontend
    role: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
